#v=1e0 m/s for du=0.25mm we need 10^8 time steps
#v=1e1 m/s for du=0.25mm we need 10^7 time steps
#timesteps = 35000
timesteps = 45000
modulo = 500
dt = 2e-9

#speed_wall_z_max = -1e-4
speed_wall_z_max = -5e-1
speed_wall_z_min = 5e-1
normal_stiffness = 6.0e29
# parallel
is_parallel = 1

# CN

allow_damping  = 1
allow_friction = 1

damping_ratio = 0.3
friction_coefficient  = 0.7
compute_wall_reaction = 1

enable_fracture = 1
self_contact = 1


# TL
do_resume   = 0
wall_resume = 0
resume_ind  = 190
save_file   = 1
nl_bdry_only= 0


# qs
quasi_static    = 0
qs_relax_steps  = 500

qs_adaptive     = 0
qs_gap_tol      = 6.57143e-05

qs_gap_factor = 1.0
qs_max_wall_step = -1 #0.25*6.57143e-05
