#timesteps = 8000
#modulo = 50
#modulo = 100

timesteps = 18000
modulo = 500

dt = 3e-8
#dt = 1.5e-5    # for rad=50

# parallel
is_parallel = 1

# TL
do_resume = 0
resume_ind = 320
save_file = 1
nl_bdry_only = 1

# CN
allow_damping = 1
allow_friction = 1

damping_ratio = 0.9
friction_coefficient = 0.7
enable_fracture=0

self_contact = 0
compute_wall_reaction = 1
#normal_stiffness = 5
enable_fracture = 0
self_contact = 0

speed_wall_z_max = -2e-2 # -2e-1 #-0.2

compute_wall_reaction =1
#----------------------
#
#// --- user-set knobs (read from config or set before the loop) ---
jump_wall=0;        #// 0/1
jump_step=100;      #  // e.g., 25000 (the step you observed in images)
z_jump=-1;          # // absolute target; set < 0 if you don't want absolute jump
jump_move_steps=3000; #  // how many steps' worth of motion to apply if not using z_jump
steps_after_jump=0;

#----------------------------------



wall_cyl = 0

#---------------small scale--------------------

# ------- N = 400  scale 1e-5---------
# Box size (Lx, Ly, Lz) = (0.00521351, 0.00515111, 0.00597321)
wall_cyl_cent_x = 0
wall_cyl_cent_y = -2.84217e-14
# wall_cyl_cent_z = -0.0029866
wall_cyl_rad    = 0.00257556













#---------------scale e-4-----------
# ------- N = 1 ---------
# Box size (Lx, Ly, Lz) = (0.0730997, 0.102314, 0.0614162)
# wall_cyl_cent_x = -2.84217e-14
# wall_cyl_cent_y = 1.42109e-14
# # wall_cyl_cent_z = -0.0307081
# wall_cyl_rad    = 0.0365498
#

# ------- N = 200 ---------
# Box size (Lx, Ly, Lz) = (0.505089, 0.517075, 0.377476)
# wall_cyl_cent_x = 0.0
# wall_cyl_cent_y = 0.0
# # wall_cyl_cent_z = -0.188738
# wall_cyl_rad    = 0.252545


# ------- N = 400 ---------
# Box size (Lx, Ly, Lz) = (0.534898, 0.517075, 0.613299)
# wall_cyl_cent_x = -2.84217e-14
# wall_cyl_cent_y = -2.84217e-14
# # wall_cyl_cent_z = -0.30665
# wall_cyl_rad    = 0.258538
#

#------- N = 10 ---------
# #Box size (Lx, Ly, Lz) = (0.481113, 0.25163, 0.100697)
# wall_cyl_cent_x = -2.84217e-14
# wall_cyl_cent_y = 0.0
# # wall_cyl_cent_z = -0.0503483
# wall_cyl_rad    = 0.125815
#
# ------- N = 60 ---------
# Box size (Lx, Ly, Lz) = (0.486679, 0.485155, 0.186189)
# wall_cyl_cent_x = 2.84217e-14
# wall_cyl_cent_y = 0.0
# # wall_cyl_cent_z = -0.0930943
# wall_cyl_rad    = 0.242578
#
#------#----------#-----------#--------#-------#
#--------------------larg scale-----------------
#  # ------- N=3 ---------
# wall_cyl_cent_x =0.264543
# wall_cyl_cent_y =0.166771
# #wall_cyl_cent_z =9.94530886
# wall_cyl_rad    = 0.0660928
# #




# #-------N=3---------
# wall_cyl_cent_x = 260
# wall_cyl_cent_y = 170
#
# wall_cyl_rad = 155 #4.1e-3
# # ------- N=1 ---------
# wall_cyl_cent_x = 374.85315533
# wall_cyl_cent_y = 154.97927187
# #wall_cyl_cent_z = -9.94530886
# wall_cyl_rad    = 57.8879018212183
#
# # ------- N=3 ---------
#  wall_cyl_cent_x = 260.45307672
#  wall_cyl_cent_y = 169.58318459
#  #wall_cyl_cent_z = -9.94530886
#  wall_cyl_rad    = 154.308761183166
# #
# # ------- N=20 ---------
# wall_cyl_cent_x = 275.60911909
# wall_cyl_cent_y = 266.85731392
# wall_cyl_rad    = 252.24209688837456
# # # ------- N=200 ---------
# wall_cyl_cent_x = 278.60582681
# wall_cyl_cent_y = 260.67984469
# wall_cyl_rad    = 255.5134143280453
# # ------- N=400 ---------
# wall_cyl_cent_x = 281.97092355
# wall_cyl_cent_y = 262.64840413
# wall_cyl_cent_z = -10.48799139
# wall_cyl_rad    = 258.8785110738453
# wall_cyl_h      = 593.4466924453716
